extends RefCounted # Keep authored merchant, barter, gift and help encounters separate from transactions.
class_name RadiantOfferCatalogue # Describe spontaneous noncombat encounters with real inventory terms.

const OFFERS: Dictionary[String, Dictionary] = { # Store distinct goals and their concrete exchange terms.
    "boot_money": {"title": "Travelling Baker", "give_id": "bread", "give_quantity": 3, "take_id": "coins", "take_quantity": 5, "opening": "My boots are worn through. I can sell you {reward} for {payment} to help pay for a new pair.", "accept": "Buy {reward} For {payment}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the boot money encounter and its actual exchange.
    "wagon_repairs": {"title": "Stranded Miner", "give_id": "iron_pickaxe", "give_quantity": 1, "take_id": "coins", "take_quantity": 12, "opening": "My wagon needs repairs. Would you buy my spare {reward} for {payment}?", "accept": "Buy {reward} For {payment}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the wagon repairs encounter and its actual exchange.
    "homeward_fare": {"title": "Homeward Soldier", "give_id": "iron_sword", "give_quantity": 1, "take_id": "coins", "take_quantity": 18, "opening": "I am trying to raise money to get home. Take {reward} for {payment}, and we both gain something.", "accept": "Buy {reward} For {payment}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the homeward fare encounter and its actual exchange.
    "knife_upgrade": {"title": "Travelling Hunter", "give_id": "hunters_knife", "give_quantity": 1, "take_id": "coins", "take_quantity": 9, "opening": "I am saving for a new blade. My spare {reward} is yours for {payment}.", "accept": "Buy {reward} For {payment}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the knife upgrade encounter and its actual exchange.
    "tent_supplies": {"title": "Cloth Seller", "give_id": "linen", "give_quantity": 4, "take_id": "coins", "take_quantity": 6, "opening": "I need coins to replace my tent supplies. Would you take {reward} for {payment}?", "accept": "Buy {reward} For {payment}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the tent supplies encounter and its actual exchange.
    "food_buyer": {"title": "Hungry Traveller", "give_id": "coins", "give_quantity": 7, "take_id": "bread", "take_quantity": 2, "opening": "My companion and I need food. I can give you {reward} for {payment}.", "accept": "Sell {payment} For {reward}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the food buyer encounter and its actual exchange.
    "cloak_buyer": {"title": "Cold Traveller", "give_id": "coins", "give_quantity": 8, "take_id": "linen", "take_quantity": 3, "opening": "My cloak has torn badly. I will pay {reward} for {payment} so I can patch it.", "accept": "Sell {payment} For {reward}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the cloak buyer encounter and its actual exchange.
    "camp_barter": {"title": "Camp Cook", "give_id": "bread", "give_quantity": 3, "take_id": "linen", "take_quantity": 2, "opening": "Our camp has spare food but needs cloth. Trade me {payment}, and take {reward}.", "accept": "Trade {payment} For {reward}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the camp barter encounter and its actual exchange.
    "traveller_barter": {"title": "Travelling Tailor", "give_id": "linen", "give_quantity": 3, "take_id": "bread", "take_quantity": 2, "opening": "I have cloth to spare and an empty stomach. Would you exchange {payment} for {reward}?", "accept": "Trade {payment} For {reward}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "Thank you. Safe travels!"}, # Describe the traveller barter encounter and its actual exchange.
    "shared_lunch": {"title": "Generous Traveller", "give_id": "bread", "give_quantity": 2, "take_id": "", "take_quantity": 0, "opening": "Good {time_of_day}! I brought more food than I need. Please take {reward}, freely.", "accept": "Accept {reward}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "You are very welcome. Safe travels!"}, # Describe the shared lunch encounter and its actual exchange.
    "spare_knife": {"title": "Grateful Hunter", "give_id": "hunters_knife", "give_quantity": 1, "take_id": "", "take_quantity": 0, "opening": "A traveller once helped me. I would like to pass that kindness on. Take {reward}; I ask nothing for it.", "accept": "Accept {reward}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "You are very welcome. Safe travels!"}, # Describe the spare knife encounter and its actual exchange.
    "lucky_coins": {"title": "Cheerful Traveller", "give_id": "coins", "give_quantity": 4, "take_id": "", "take_quantity": 0, "opening": "The road has been kind to me today. Have {reward}, with my good wishes.", "accept": "Accept {reward}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "You are very welcome. Safe travels!"}, # Describe the lucky coins encounter and its actual exchange.
    "cloth_gift": {"title": "Helpful Tailor", "give_id": "linen", "give_quantity": 2, "take_id": "", "take_quantity": 0, "opening": "I have some cloth left over. Take {reward}; it may prove useful on your travels.", "accept": "Accept {reward}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "You are very welcome. Safe travels!"}, # Describe the cloth gift encounter and its actual exchange.
    "stranded_traveller": {"title": "Stranded Traveller", "give_id": "", "give_quantity": 0, "take_id": "coins", "take_quantity": 3, "opening": "I am short of money for supplies. Could you spare {payment}? I have nothing to offer in return.", "accept": "Give {payment}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 10.0, "success": "Thank you. Safe travels!"}, # Describe the stranded traveller encounter and its actual exchange.
    "hungry_traveller": {"title": "Weary Traveller", "give_id": "", "give_quantity": 0, "take_id": "bread", "take_quantity": 1, "opening": "I have eaten nothing for hours. Could you spare {payment}? I cannot pay you back.", "accept": "Give {payment}", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 10.0, "success": "Thank you. Safe travels!"}, # Describe the hungry traveller encounter and its actual exchange.
    "local_news": {"title": "Local Traveller", "give_id": "", "give_quantity": 0, "take_id": "", "take_quantity": 0, "opening": "Good {time_of_day}, traveller. I have a little local knowledge to share. Would you like to hear it?", "accept": "Hear The Local News", "decline": "No, Thank You", "hostile_on_accept": false, "affection_gain": 5.0, "success": "You are very welcome. Safe travels!"}, # Describe the local news encounter and its actual exchange.
} # Finish the authored noncombat encounter catalogue.

static func kinds() -> Array[String]: # Expose selectable event identifiers without mutable catalogue access.
    var result: Array[String] = [] # Retain strongly typed event identifiers.
    result.assign(OFFERS.keys()) # Copy the authored event keys.
    return result # Let the director shuffle one finite encounter bag.

static func definition(kind: String) -> Dictionary: # Return an independent offer quote for one event actor.
    if not OFFERS.has(kind): # Reject unsupported identifiers safely.
        return {} # Leave current inventory and dialogue ownership unchanged.
    var result: Dictionary = OFFERS[kind].duplicate(true) # Isolate per-actor rendering and completion state.
    result["kind"] = kind # Keep the quote linked to its authored event type.
    return result # Preserve exact terms throughout this encounter.
