extends SceneTree
func _initialize(): run.call_deferred()
func run():
    LootSession.records.clear()
    var game = Node3D.new()
    root.add_child(game)
    var world = load("res://world/environments/basic_world.tscn").instantiate()
    world.name = "World"
    game.add_child(world)
    world.set_process(false)
    var terrain = world.get_node("Terrain")
    terrain.set_process(false)
    var entities = Node3D.new()
    entities.name = "DynamicEntities"
    game.add_child(entities)
    var player = load("res://actors/player/first_person_player.tscn").instantiate()
    player.name = "Player"
    entities.add_child(player)
    player.set_physics_process(false)
    var inventory = player.get_node("PlayerInventory")
    var chest = LootChest.new()
    chest.loot_key = "test-chest"
    chest.seed_value = 19
    world.add_child(chest)
    var storage = chest.get_loot_inventory()
    var coins = storage.get_stack_at(0).get_quantity()
    assert(LootStorage.transfer(storage,inventory,&"coins",1))
    assert(storage.get_stack_at(0).get_quantity() == coins-1)
    assert(LootStorage.transfer(inventory,storage,&"coins",1))
    assert(storage.get_stack_at(0).get_quantity() == coins)
    assert(not LootStorage.transfer(storage,inventory,&"coins",coins+1))
    assert(storage.get_stack_at(0).get_quantity() == coins)
    storage.try_add_item(&"heavy","Heavy stone",1000,1)
    var revision = storage.get_revision()
    assert(not LootStorage.transfer(storage,inventory,&"heavy",1))
    assert(storage.get_revision() == revision)
    assert(not LootStorage.transfer(storage,storage,&"coins",1))
    storage.try_add_item(&"conflict","Conflicting item",.1,1)
    inventory.try_add_item(&"conflict","Conflicting item",.2,1)
    assert(not LootStorage.transfer(storage,inventory,&"conflict",1))
    var ui = LootUI.new()
    game.add_child(ui)
    ui.set_process(false)
    ui.open_loot(chest)
    assert(ui._panel.visible and ui._lists[0].item_count == storage.get_stack_count())
    ui._lists[0].select(0)
    ui._lists[0].get_parent().get_child(2).get_child(0).pressed.emit()
    assert(storage.get_stack_at(0).get_quantity() == coins-1)
    ui.close_loot()
    assert(not ui._panel.visible)
    chest.free()
    chest = LootChest.new()
    chest.loot_key = "test-chest"
    chest.seed_value = 19
    world.add_child(chest)
    assert(chest.get_loot_inventory() == storage)
    assert(storage.get_stack_at(0).get_quantity() == coins-1)
    var sampler = VillagerPopulationSampler.new(terrain)
    var town = sampler._settlements.find_nearby(Vector2.ZERO,"town")
    var definition = sampler.town(town)[0]
    var npc = Villager.new()
    npc.configure(terrain,definition)
    world.add_child(npc)
    npc.set_physics_process(false)
    npc.set_process(false)
    assert(npc.get_loot_inventory() == null)
    var hit = EquipmentHit.new()
    hit.damage = 120
    npc.receive_equipment_hit(hit)
    assert(npc.get_loot_inventory() != null)
    assert(not npc.perform_action("punch"))
    var belongings = npc.get_loot_inventory()
    assert(LootStorage.transfer(inventory,belongings,&"coins",1))
    var position_world = npc.world_position
    npc.free()
    npc = Villager.new()
    npc.configure(terrain,definition)
    world.add_child(npc)
    npc.set_physics_process(false)
    assert(npc.get_loot_inventory() == belongings)
    assert(npc.world_position == position_world)
    player.global_position = npc.global_position+Vector3(0,0,2)
    player.set_physics_process(true)
    var camera = player.get_view_camera()
    camera.look_at(npc.global_position+Vector3(0,.25,0))
    await physics_frame
    await process_frame
    assert(ui._ray_target() == npc,"A dead NPC must be searchable through the interaction ray")
    var wall = StaticBody3D.new()
    var shape_node = CollisionShape3D.new()
    var shape = BoxShape3D.new()
    shape.size = Vector3(2,2,.2)
    shape_node.shape = shape
    wall.add_child(shape_node)
    world.add_child(wall)
    wall.global_position = camera.global_position.lerp(npc.global_position+Vector3(0,.25,0),.5)
    await physics_frame
    await process_frame
    assert(ui._ray_target() == null,"Loot must not be accessible through a wall")
    player.set_physics_process(false)
    wall.free()
    ui.open_loot(npc)
    npc.health.heal(20)
    assert(npc.get_loot_inventory() == null)
    assert(is_zero_approx(npc._visual.rotation.z))
    ui._process(0)
    assert(not ui._panel.visible)
    game.free()
    LootSession.records.clear()
    print("PASS: atomic two-way transfers, capacity/conflict rejection, shared loot UI, chest contents survive streaming, melee death unlocks loot, corpse contents and location survive reloading.")
    quit()
