extends SceneTree
func _initialize(): run.call_deferred()
func run():
    var player = PlayerVitals.new()
    var npc = DamageableHealth.new()
    root.add_child(player)
    root.add_child(npc)
    var deaths = [0]
    npc.died.connect(func(): deaths[0] += 1)
    assert(player.get_health() == 100 and npc.get_health() == 100)
    for actor in [player,npc]:
        assert(actor.apply_damage(25) == 25)
        assert(actor.get_health() == 75)
        assert(actor.apply_damage(-2) == 0)
        assert(actor.apply_damage(NAN) == 0)
        assert(actor.heal(10) == 10)
        actor.set_maximum_health(50)
        assert(actor.get_health() == 50)
        actor.set_maximum_health(150)
        assert(actor.get_health() == 50)
        actor.set_infinite_health_enabled(true)
        assert(actor.get_health() == 150)
        assert(actor.apply_damage(999) == 0)
        actor.set_health(1)
        assert(actor.get_health() == 150)
        actor.set_infinite_health_enabled(false)
        assert(actor.apply_damage(999) == 150)
        assert(actor.is_dead())
        assert(actor.apply_damage(1) == 0)
        assert(actor.heal(20) == 20)
        assert(not actor.is_dead())
        var revision = actor.get_revision()
        actor.set_health(20)
        assert(actor.get_revision() == revision)
    assert(deaths[0] == 1)
    var tiny = HealthState.new()
    tiny.set_health(.000001)
    assert(tiny.apply_damage(1) > 0 and tiny.is_dead())
    var stamina = player.get_stamina()
    player.consume_stamina(10)
    assert(player.get_stamina() == stamina-10)
    assert(player.get_health() == 20)
    LootSession.records.clear()
    var record = LootSession.get_record("health-persistence",17,true)
    npc.bind_state(record.health)
    npc.apply_damage(31)
    var replacement = DamageableHealth.new()
    replacement.bind_state(LootSession.get_record("health-persistence",17,true).health)
    assert(replacement.get_health() == 69)
    replacement.heal(5)
    assert(npc.get_health() == 74)
    replacement.free()
    player.free()
    npc.free()
    LootSession.records.clear()
    print("PASS: shared player/NPC defaults, damage, healing, maximum changes, protection, death/revival, revisions, independent stamina and streamed health state.")
    quit()
