extends SceneTree
func _initialize(): run.call_deferred()
func run():
    var game = Node3D.new()
    root.add_child(game)
    var world = load("res://world/environments/basic_world.tscn").instantiate()
    world.name = "World"
    game.add_child(world)
    world.set_process(false)
    var terrain = world.get_node("Terrain")
    terrain.set_process(false)
    var entities = Node3D.new()
    entities.name = "DynamicEntities"
    game.add_child(entities)
    var player = load("res://actors/player/first_person_player.tscn").instantiate()
    player.name = "Player"
    entities.add_child(player)
    player.set_physics_process(false)
    var profiler = RuntimeProfiler.new()
    game.add_child(profiler)
    assert(not RuntimeProfiler.recording and not profiler.is_processing())
    assert(RuntimeProfiler.begin("disabled") == -1)
    assert(profiler.export_report().begins_with("No recording"))
    assert(profiler.start().begins_with("Profiler recording"))
    assert(profiler.start().begins_with("Already recording"))
    var parent = RuntimeProfiler.begin("test.parent")
    var child = RuntimeProfiler.begin("test.child")
    for i in range(2000): hash(str(i))
    RuntimeProfiler.end(child)
    RuntimeProfiler.end(parent)
    var terrain_mesh: ArrayMesh = terrain._mesh_builder.build_chunk_mesh(Vector2i.ZERO)
    assert(terrain_mesh != null)
    assert(RuntimeProfiler._totals.has("terrain.mesh"))
    # Timed wrappers retain return values and close spans even on early returns.
    var sampler = WayshrineSampler.for_terrain(terrain)
    assert(not sampler.suitable(BiomeProfile.region(Vector2i(0,-1)).centre))
    assert(RuntimeProfiler._stack.is_empty())
    assert(profiler.mark("walking near water").begins_with("Marked"))
    for frame in range(5): await process_frame
    profiler.stop()
    assert(not RuntimeProfiler.recording and not profiler.is_processing())
    assert(profiler._frames.size() > 0 and profiler._samples.size() > 0)
    var total: Dictionary = RuntimeProfiler._totals["test.parent"]
    assert(total.inclusive_us >= total.self_us and total.inclusive_us >= RuntimeProfiler._totals["test.child"].inclusive_us)
    var message = profiler.export_report()
    assert(message.begins_with("Profiler report saved:"),message)
    var file = FileAccess.open(profiler.last_export_path,FileAccess.READ)
    assert(file != null)
    var parsed = JSON.parse_string(file.get_as_text())
    file.close()
    assert(parsed.schema_version == 1 and parsed.summary.frames == profiler._frames.size())
    assert(parsed.markers[0].label == "walking near water")
    assert(parsed.systems.size() >= 3 and parsed.samples[0].context.npcs.loaded == 0)
    assert(parsed.environment.display_driver == "headless")
    assert(parsed.samples[0].render_gpu_ms == null)
    assert(RuntimeProfiler.percentile([1.0,2.0,3.0,4.0],.95) == 4)
    assert(profiler.export_report().begins_with("Profiler report saved:"),"Stopped report could not be exported again")
    profiler.start()
    assert(profiler._frames.is_empty() and profiler._markers.is_empty() and RuntimeProfiler._totals.is_empty())
    profiler._frames.resize(RuntimeProfiler.MAX_FRAMES-1)
    profiler._frames.fill(1.0)
    profiler._process(.01)
    assert(not RuntimeProfiler.recording and profiler._stop_reason.begins_with("capture limit"))
    game.queue_free()
    await process_frame
    assert(RuntimeProfiler.instance == null and not RuntimeProfiler.recording)
    print("PASS disabled idle, recording/reset/stop/caps, nested inclusive/self scopes, real terrain timing, early returns, markers, frame/context counters, JSON export and repeat export")
    quit()
